### ISSUE TITLE
Shulkerboxes are empty after restart

### ISSUE THREAD

**Issue by Platinteufel** [Pluckerpluck/MultiInv#40]
@Tux2 @Pluckerpluck Unfortunately I've got a quite urgent issue to be solved.
It seems like shulkerboxes in inventory/enderchest are empty after a restart. Does MultiInv save them correctly yet? If not, a hotfix would be awesome as this will cause a lot of lost items.
Thanks!
https://youtu.be/S7heN34gVBA

**Comment by Platinteufel** [comment]
Any updates here? More and more players are loosing their stuff in shulkerboxes.

**Comment by Pluckerpluck** [comment]
Alas, I no longer play minecraft.... I don't even know what a shulkerbox is!

The codebase has changed enough that I don't feel confident messing around with it. So you need to rely on @Tux2 or another noble soul to fix it.

**Comment by Tux2** [comment]
Hey, I have a solution I'm working on right now, however, since the file format isn't suited for saving items within items I'm having to rework it.

**Comment by Platinteufel** [comment]
Thank you very much for all your efforts, Tux2!

**Comment by Tux2** [comment]
Hey, just finished writing shulker box support. Enjoy!

**Comment by Platinteufel** [comment]
Thanks a lot!
